# Generated by Django 4.2 on 2026-05-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulantes', '0001_initial'),
        ('selectores', '0001_initial'),
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('recibida', 'Recibida por Empresa'), ('entrevista', 'En Entrevista'), ('oferta', 'Oferta Realizada'), ('aceptada_postulante', 'Aceptada por Postulante'), ('contratado', 'Contratado'), ('rechazada_empresa', 'Rechazada por Empresa'), ('rechazada_postulante', 'Rechazada por Postulante'), ('cancelada', 'Cancelada')], default='enviada', max_length=30)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion_empresa', models.DateTimeField(blank=True, null=True)),
                ('fecha_primera_entrevista', models.DateTimeField(blank=True, null=True)),
                ('fecha_oferta', models.DateTimeField(blank=True, null=True)),
                ('fecha_aceptacion_postulante', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_laboral', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('puntaje_empresa', models.PositiveIntegerField(blank=True, help_text='Puntaje dado por la empresa (1-10)', null=True)),
                ('feedback_empresa', models.TextField(blank=True, help_text='Feedback de la empresa sobre el postulante')),
                ('motivo_rechazo', models.CharField(blank=True, help_text='Motivo en caso de rechazo', max_length=255)),
                ('notas_selector', models.TextField(blank=True, help_text='Notas privadas del selector')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del equipo administrativo')),
                ('perfil_busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empresas.perfilbusqueda')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='postulantes.postulante')),
                ('selector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones', to='selectores.selector')),
            ],
            options={
                'db_table': 'postulaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_garantia', models.PositiveIntegerField(default=90, help_text='Días que el postulante debe estar empleado')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('completada', 'Completada (Garantía OK)'), ('incumplida', 'Incumplida (Necesita Reemplazo)'), ('anulada', 'Anulada')], default='vigente', max_length=20)),
                ('fecha_fin_real', models.DateField(blank=True, help_text='Fecha en que terminó el contrato (si fue antes de vencimiento)', null=True)),
                ('motivo_incumplimiento', models.CharField(blank=True, choices=[('empresa_despidio', 'Empresa despidió al empleado'), ('postulante_renuncio', 'Postulante renunció'), ('acuerdo', 'Acuerdo mutuo'), ('otro', 'Otro')], max_length=255)),
                ('notas', models.TextField(blank=True)),
                ('perfil_busqueda_reemplazo', models.ForeignKey(blank=True, help_text='Nueva búsqueda sin comisión para reemplazo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_incumplidas', to='empresas.perfilbusqueda')),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantia', to='postulaciones.postulacion')),
                ('postulacion_reemplazo', models.ForeignKey(blank=True, help_text='Postulación del postulante de reemplazo (sin comisión)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_reemplazo_de', to='postulaciones.postulacion')),
            ],
            options={
                'db_table': 'seguimiento_garantia',
            },
        ),
        migrations.CreateModel(
            name='HistorialPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='postulaciones.postulacion')),
            ],
            options={
                'db_table': 'historial_postulacion',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='EntrevistaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seleccion', 'Entrevista de Selección'), ('tecnica', 'Entrevista Técnica'), ('rrhh', 'Entrevista RRHH'), ('final', 'Entrevista Final')], default='seleccion', max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('entrevistador', models.CharField(help_text='Nombre/Email de quien realiza la entrevista', max_length=255)),
                ('usa_google_meet', models.BooleanField(default=True)),
                ('google_meet_url', models.URLField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, help_text='ID del evento en Google Calendar', max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Si es presencial', max_length=255)),
                ('realizada', models.BooleanField(default=False)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('no_evaluado', 'No Evaluado'), ('favorable', 'Favorable'), ('revisar', 'A Revisar'), ('desfavorable', 'Desfavorable'), ('no_asistio', 'No Asistió')], default='no_evaluado', max_length=50)),
                ('comentarios_entrevistador', models.TextField(blank=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='postulaciones.postulacion')),
            ],
            options={
                'db_table': 'entrevistas_agendadas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['estado'], name='postulacion_estado_692f93_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['postulante', 'estado'], name='postulacion_postula_ea4ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['perfil_busqueda', 'estado'], name='postulacion_perfil__9b1cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['-fecha_envio'], name='postulacion_fecha_e_42e208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('postulante', 'perfil_busqueda')},
        ),
    ]
