# Generated by Django 4.2 on 2026-05-30 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrevista', models.DateField(default=django.utils.timezone.now)),
                ('empresa_puesto_actual', models.CharField(blank=True, max_length=255)),
                ('experiencia_detalle', models.TextField(blank=True, help_text='Años de experiencia, tecnologías, herramientas usadas, etc.')),
                ('formacion_academica', models.TextField(blank=True, help_text='Título obtenido, en curso, etc.')),
                ('situacion_actual', models.CharField(blank=True, help_text='Trabajando, desempleado, en búsqueda, etc.', max_length=100)),
                ('sueldo_bruto_pretendido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comentarios_selector', models.TextField(blank=True, help_text='Comentarios y punto de vista del selector')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_entrevista', to='postulaciones.postulacion')),
            ],
            options={
                'db_table': 'informes_entrevista',
                'ordering': ['-fecha_entrevista'],
            },
        ),
    ]
