# Generated by Django 4.2 on 2026-05-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selectores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('area', models.CharField(choices=[('it', 'IT'), ('admin', 'Administrativo'), ('ejecutivo', 'Ejecutivo/Jerárquico'), ('otro', 'Otro')], max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['area', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiere_no_decir', 'Prefiere no decir')], max_length=20)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('disponibilidad_mudanza', models.BooleanField(default=False)),
                ('titulo_principal', models.CharField(help_text='Ej: Desarrollador Python Senior', max_length=255)),
                ('resumen_profesional', models.TextField(blank=True, help_text='Resumen ejecutivo de experiencia')),
                ('experiencia_anos', models.PositiveIntegerField(default=0, help_text='Años de experiencia laboral')),
                ('titulaciones', models.TextField(blank=True, help_text='Títulos obtenidos (separados por comas)')),
                ('habilidades', models.TextField(blank=True, help_text='Habilidades clave (separadas por comas)')),
                ('idiomas', models.CharField(blank=True, help_text='Ej: Español (Nativo), Inglés (B2), Francés (A2)', max_length=255)),
                ('salario_pretendido_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salario_pretendido_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('acepta_remoto', models.BooleanField(default=True)),
                ('acepta_hibrido', models.BooleanField(default=True)),
                ('acepta_presencial', models.BooleanField(default=True)),
                ('cv_archivo', models.FileField(blank=True, help_text='PDF del CV', null=True, upload_to='cvs/%Y/%m/%d/')),
                ('cv_texto_extraido', models.TextField(blank=True, help_text='Texto del CV extraído para búsqueda')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo (Disponible)'), ('en_proceso', 'En Proceso'), ('contratado', 'Contratado'), ('rechazo_empresa', 'Rechazado por Empresa'), ('rechazo_postulante', 'Rechazado por Postulante'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('contactado_reciente', models.BooleanField(default=False)),
                ('fecha_ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('google_contact_id', models.CharField(blank=True, help_text='ID del contacto en Google Contacts', max_length=255, null=True)),
                ('categorias', models.ManyToManyField(related_name='postulantes', to='postulantes.categoria')),
                ('selector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes_cargados', to='selectores.selector')),
            ],
            options={
                'db_table': 'postulantes',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='TituloPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='postulantes.postulante')),
            ],
            options={
                'db_table': 'titulos_postulante',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='NotaPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('contenido', models.TextField()),
                ('privada', models.BooleanField(default=False, help_text='Si es privada, solo el autor y admin la ven')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_escritas', to='selectores.selector')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='postulantes.postulante')),
            ],
            options={
                'db_table': 'notas_postulante',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('entrevista', 'Entrevista Confirmada')], max_length=20)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('google_event_id', models.CharField(blank=True, help_text='ID del evento en Google Calendar', max_length=255, null=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='postulantes.postulante')),
            ],
            options={
                'db_table': 'disponibilidad_postulante',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['email'], name='postulantes_email_ac35b6_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['estado'], name='postulantes_estado_69fc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['selector'], name='postulantes_selecto_bf472e_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['-fecha_carga'], name='postulantes_fecha_c_fec6f9_idx'),
        ),
    ]
