# Generated by Django 4.2 on 2026-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='selector_dni',
            field=models.CharField(blank=True, help_text='DNI del selector que presenta al candidato', max_length=20, null=True),
        ),
    ]
