# Generated by Django 4.2 on 2026-05-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0002_postulante_selector_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='selector_dni',
        ),
        migrations.AddField(
            model_name='postulante',
            name='selector_cuit',
            field=models.CharField(blank=True, help_text='CUIT del selector que presenta al candidato', max_length=20, null=True),
        ),
    ]
