# Generated by Django 4.2 on 2026-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0003_remove_postulante_selector_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='guardado_en_pool',
            field=models.BooleanField(default=True, help_text='Indica si pertenece a la Base de Datos de Talentos general de la consultora'),
        ),
    ]
