# Generated by Django 4.2 on 2026-05-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0004_postulante_guardado_en_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
