# Generated by Django 4.2 on 2026-05-31 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def populate_default_states_and_migrate(apps, schema_editor):
    EstadoPostulante = apps.get_model('postulantes', 'EstadoPostulante')
    Postulante = apps.get_model('postulantes', 'Postulante')

    # Create default states
    states_data = [
        {'nombre': 'Activo', 'color': '#34c759', 'no_borrable': True, 'orden': 1},
        {'nombre': 'En evaluación', 'color': '#0a84ff', 'no_borrable': True, 'orden': 2},
        {'nombre': 'Rechazado', 'color': '#ff3b30', 'no_borrable': True, 'orden': 3},
        {'nombre': 'Referido a la empresa', 'color': '#ff9f0a', 'no_borrable': True, 'orden': 4},
        {'nombre': 'Rechazado por empresa', 'color': '#ff6b35', 'no_borrable': True, 'orden': 5},
        {'nombre': 'Contratado', 'color': '#9333ea', 'no_borrable': True, 'orden': 6},
    ]

    states_objs = {}
    for sd in states_data:
        obj, _ = EstadoPostulante.objects.get_or_create(
            nombre=sd['nombre'],
            defaults={'color': sd['color'], 'no_borrable': sd['no_borrable'], 'orden': sd['orden']}
        )
        states_objs[sd['nombre'].lower()] = obj

    mapping = {
        'activo': states_objs['activo'],
        'en_proceso': states_objs['en evaluación'],
        'contratado': states_objs['contratado'],
        'rechazo_empresa': states_objs['rechazado por empresa'],
        'rechazo_postulante': states_objs['rechazado'],
        'inactivo': states_objs['rechazado'],
    }

    for p in Postulante.objects.all():
        old_state_str = str(p.estado_old).lower() if p.estado_old else 'activo'
        target_state = mapping.get(old_state_str, states_objs['activo'])
        p.estado = target_state
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0005_alter_postulante_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#34c759', max_length=7)),
                ('no_borrable', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estados_postulante',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveIndex(
            model_name='postulante',
            name='postulantes_estado_69fc2f_idx',
        ),
        migrations.RenameField(
            model_name='postulante',
            old_name='estado',
            new_name='estado_old',
        ),
        migrations.AddField(
            model_name='postulante',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postulantes', to='postulantes.estadopostulante'),
        ),
        migrations.RunPython(populate_default_states_and_migrate),
        migrations.RemoveField(
            model_name='postulante',
            name='estado_old',
        ),
        migrations.AddField(
            model_name='postulante',
            name='fecha_cambio_estado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['estado'], name='postulantes_estado__93e44a_idx'),
        ),
    ]

