# Generated by Django 6.0.5 on 2026-06-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0006_estadopostulante_and_more'),
        ('selectores', '0003_gruposelector_selector_grupos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['estado', 'titulo_principal'], name='postulantes_estado__537630_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['ciudad', 'provincia'], name='postulantes_ciudad_429bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='postulante',
            index=models.Index(fields=['estado', '-fecha_carga'], name='postulantes_estado__3174ab_idx'),
        ),
    ]
