# Generated by Django 6.0.5 on 2026-06-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0007_postulante_postulantes_estado__537630_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopostulante',
            name='enviar_email_automatico',
            field=models.BooleanField(default=False, help_text='Enviar email al candidato automáticamente cuando entra a este estado.'),
        ),
        migrations.AddField(
            model_name='estadopostulante',
            name='plantilla_email',
            field=models.TextField(blank=True, help_text='Plantilla del correo. Usar variables como {{nombre}}, {{empresa}}.'),
        ),
    ]
