# Generated by Django 6.0.5 on 2026-06-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0008_estadopostulante_enviar_email_automatico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='estadopostulante',
            name='plantilla_whatsapp',
            field=models.TextField(blank=True, help_text='Plantilla para WhatsApp. Usar variables como {{nombre}}, {{empresa}}.'),
        ),
    ]
