# Generated by Django 6.0.5 on 2026-06-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0009_whatsappmessage_estadopostulante_plantilla_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria_sugerida', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'habilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('peso', models.IntegerField(default=0, help_text='Para ordenamiento (ej: Posgrado > Universitario)')),
            ],
            options={
                'db_table': 'niveles_estudio',
                'ordering': ['-peso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipos_empleo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='postulante',
            name='habilidades_validadas',
            field=models.ManyToManyField(blank=True, related_name='postulantes_con_habilidad', to='postulantes.habilidad'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='nivel_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postulantes.nivelestudio'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='tipos_empleo',
            field=models.ManyToManyField(blank=True, related_name='postulantes_interesados', to='postulantes.tipoempleo'),
        ),
    ]
