# Generated by Django 4.2 on 2026-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0010_habilidad_nivelestudio_tipoempleo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='guardado_en_pool',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si pertenece a la Base de Datos de Talentos general de la consultora'),
        ),
    ]
