# Generated by Django 4.2 on 2026-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones_google', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletoken',
            name='global_form_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googletoken',
            name='global_form_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
