# Generated by Django 4.2 on 2026-05-14 22:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('es_contacto_principal', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contactos_empresa',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial de la empresa', max_length=255, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_empresa', models.CharField(choices=[('privada', 'Empresa Privada'), ('publica', 'Empresa Pública')], default='privada', max_length=10)),
                ('email_principal', models.EmailField(max_length=254, unique=True)),
                ('email_alterno', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField(blank=True, help_text='Coordenada GPS', null=True)),
                ('longitud', models.FloatField(blank=True, help_text='Coordenada GPS', null=True)),
                ('contacto_nombre', models.CharField(max_length=255)),
                ('contacto_email', models.EmailField(max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_puesto', models.CharField(blank=True, max_length=100)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=20.0, help_text='Porcentaje de comisión sobre salario del contratado (ej: 20.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('salario_promedio_ofrecido', models.DecimalField(blank=True, decimal_places=2, help_text='Referencia de salario promedio que ofrece', max_digits=12, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_busqueda', models.DateTimeField(blank=True, null=True)),
                ('google_contact_id', models.CharField(blank=True, help_text='ID del contacto en Google Contacts', max_length=255, null=True)),
                ('google_calendar_id', models.CharField(blank=True, help_text='ID del calendario de Google Calendar', max_length=255, null=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_puesto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada del puesto')),
                ('areas', models.CharField(choices=[('it', 'IT'), ('admin', 'Administrativo'), ('ejecutivo', 'Ejecutivo/Jerárquico'), ('otro', 'Otro')], max_length=50)),
                ('nivel', models.CharField(choices=[('senior', 'Senior (5+ años)'), ('semi_senior', 'Semi Senior (2-4 años)'), ('junior', 'Junior (0-1 años)'), ('practicante', 'Practicante')], default='semi_senior', max_length=20)),
                ('habilidades_requeridas', models.TextField(help_text='Lista de habilidades requeridas (separadas por comas)')),
                ('educacion_minima', models.CharField(blank=True, help_text='Ej: Licenciatura en Informática, Contador Público, etc.', max_length=255)),
                ('experiencia_minima_anios', models.PositiveIntegerField(default=1, help_text='Años de experiencia mínimos requeridos')),
                ('es_remoto', models.BooleanField(default=False)),
                ('ubicacion_puesto', models.CharField(blank=True, max_length=255)),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('salario_maximo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('beneficios', models.TextField(blank=True, help_text='Beneficios ofrecidos (obra social, bono, etc)')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('pausa', 'Pausa Temporal'), ('cubierto', 'Perfil Cubierto'), ('cancelado', 'Cancelado')], default='abierto', max_length=20)),
                ('cantidad_posiciones', models.PositiveIntegerField(default=1, help_text='Cantidad de posiciones disponibles')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite para llenar la posición', null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('notas_internas', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_busqueda', to='empresas.empresa')),
            ],
            options={
                'db_table': 'perfiles_busqueda',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
