# Generated by Django 4.2 on 2026-05-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('selectores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='selector_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_asignados', to='selectores.selector'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['email_principal'], name='empresas_email_p_5f17e0_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['activa'], name='empresas_activa_0b856e_idx'),
        ),
        migrations.AddField(
            model_name='contactoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='empresas.empresa'),
        ),
        migrations.AddIndex(
            model_name='perfilbusqueda',
            index=models.Index(fields=['empresa', 'estado'], name='perfiles_bu_empresa_e11d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilbusqueda',
            index=models.Index(fields=['areas'], name='perfiles_bu_areas_b6e989_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactoempresa',
            unique_together={('empresa', 'email')},
        ),
    ]
