# Generated by Django 4.2 on 2026-05-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='comision_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión específica para esta búsqueda (sobreescribe la de la empresa)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='flyer_url',
            field=models.URLField(blank=True, help_text='Link al archivo de Flyer promocional en Google Drive', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='jd_url',
            field=models.URLField(blank=True, help_text='Link al documento de Job Description (JD) de Google Docs', max_length=500, null=True),
        ),
    ]
