# Generated by Django 4.2 on 2026-05-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_perfilbusqueda_comision_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='jornada_laboral',
            field=models.CharField(blank=True, help_text='Días y horarios de trabajo. Ej: Lunes a Viernes de 9 a 18 hs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='mision_puesto',
            field=models.TextField(blank=True, help_text='Misión u objetivo principal del puesto', null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='requisitos_deseables',
            field=models.TextField(blank=True, help_text='Requisitos deseables, complementarios o valorados (uno por línea)', null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='requisitos_excluyentes',
            field=models.TextField(blank=True, help_text='Requisitos excluyentes o indispensables (uno por línea)', null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='responsabilidades',
            field=models.TextField(blank=True, help_text='Responsabilidades y tareas clave del puesto (una por línea o viñetas)', null=True),
        ),
    ]
