# Generated by Django 4.2 on 2026-05-18 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_perfilbusqueda_jornada_laboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'db_table': 'rubros',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_comercial_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_comercial_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_comercial_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_comercial_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='garantia',
            field=models.CharField(choices=[('con_garantia', 'Con garantía'), ('sin_garantia', 'Sin garantía')], default='con_garantia', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modalidad_contratacion',
            field=models.CharField(choices=[('a_riesgo', 'A riesgo'), ('con_anticipo', 'Con anticipo')], default='a_riesgo', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='empresas.rubro'),
        ),
    ]
