# Generated by Django 4.2 on 2026-05-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_rubro_empresa_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='flyer_imagen',
            field=models.ImageField(blank=True, help_text='Imagen del flyer generado para promoción en redes', null=True, upload_to='flyers/'),
        ),
    ]
