# Generated by Django 4.2 on 2026-05-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_perfilbusqueda_flyer_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='candidato_ideal',
            field=models.TextField(blank=True, help_text='Descripción del perfil del candidato ideal', null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='convenio',
            field=models.CharField(blank=True, help_text='Convenio colectivo aplicable (ej: SMATA, Fuera de convenio)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='descansos',
            field=models.CharField(blank=True, help_text='Tiempos de descanso/breaks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='edad_rango',
            field=models.CharField(blank=True, help_text='Rango de edad sugerido', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha estimada de inicio', null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones o notas de entrega importantes', null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='preguntas_informe',
            field=models.TextField(blank=True, help_text='Preguntas filtro a incluir en el informe de entrevista', null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='zona_residencia',
            field=models.CharField(blank=True, help_text='Zona de residencia sugerida', max_length=255, null=True),
        ),
    ]
