# Generated by Django 4.2 on 2026-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_perfilbusqueda_google_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='codigo_busqueda',
            field=models.CharField(blank=True, help_text='Código único de la búsqueda para sincronización global', max_length=100, null=True, unique=True),
        ),
    ]
