# Generated by Django 4.2 on 2026-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_perfilbusqueda_codigo_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código identificador de 4 caracteres para la empresa', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='codigo_puesto',
            field=models.CharField(blank=True, help_text='Código de puesto de 4 caracteres (ej: DESA)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='codigo_titulo',
            field=models.CharField(blank=True, help_text='Código de profesión/título de 4 caracteres (ej: CONT)', max_length=4, null=True),
        ),
    ]
