# Generated by Django 4.2 on 2026-05-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_empresa_codigo_perfilbusqueda_codigo_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 4 letras (ej: DESA)', max_length=4, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del puesto (ej: Desarrollador)', max_length=100)),
            ],
            options={
                'verbose_name': 'Código de Puesto',
                'verbose_name_plural': 'Códigos de Puesto',
                'db_table': 'codigos_puesto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 4 letras (ej: CONT)', max_length=4, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la profesión o título (ej: Contador)', max_length=100)),
            ],
            options={
                'verbose_name': 'Código de Título',
                'verbose_name_plural': 'Códigos de Título',
                'db_table': 'codigos_titulo',
                'ordering': ['nombre'],
            },
        ),
    ]
