# Generated by Django 4.2 on 2026-05-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_codigopuesto_codigotitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='salario_estipulado_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario estipulado para pago de comisión', max_digits=12, null=True),
        ),
    ]
