# Generated by Django 4.2 on 2026-05-31 15:29

from django.db import migrations, models
import django.db.models.deletion

def migrate_existing_states(apps, schema_editor):
    EstadoBusqueda = apps.get_model('empresas', 'EstadoBusqueda')
    PerfilBusqueda = apps.get_model('empresas', 'PerfilBusqueda')

    # Create default states
    s_abierto, _ = EstadoBusqueda.objects.get_or_create(
        nombre='Abiertas',
        defaults={'color': '#34c759', 'no_borrable': True, 'orden': 1}
    )
    s_pausa, _ = EstadoBusqueda.objects.get_or_create(
        nombre='En Pausa',
        defaults={'color': '#ffcc00', 'no_borrable': True, 'orden': 2}
    )
    s_cubierto, _ = EstadoBusqueda.objects.get_or_create(
        nombre='Cubiertas',
        defaults={'color': '#0a84ff', 'no_borrable': True, 'orden': 3}
    )
    s_cancelado, _ = EstadoBusqueda.objects.get_or_create(
        nombre='Canceladas',
        defaults={'color': '#ff3b30', 'no_borrable': True, 'orden': 4}
    )

    mapping = {
        'abierto': s_abierto,
        'pausa': s_pausa,
        'cubierto': s_cubierto,
        'cancelado': s_cancelado
    }

    for perfil in PerfilBusqueda.objects.all():
        old_val = getattr(perfil, 'estado_old', None)
        if old_val:
            old_val_lower = old_val.lower()
            if old_val_lower in mapping:
                perfil.estado = mapping[old_val_lower]
                perfil.save()
            else:
                perfil.estado = s_abierto
                perfil.save()
        else:
            perfil.estado = s_abierto
            perfil.save()

class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_perfilbusqueda_salario_estipulado_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#34c759', max_length=7)),
                ('no_borrable', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estados_busqueda',
                'ordering': ['orden', 'nombre'],
            },
        ),
        # Drop Index to avoid SQLite issues
        migrations.RemoveIndex(
            model_name='perfilbusqueda',
            name='perfiles_bu_empresa_e11d1a_idx',
        ),
        migrations.RenameField(
            model_name='perfilbusqueda',
            old_name='estado',
            new_name='estado_old',
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_busqueda', to='empresas.estadobusqueda'),
        ),
        migrations.RunPython(migrate_existing_states),
        migrations.RemoveField(
            model_name='perfilbusqueda',
            name='estado_old',
        ),
        migrations.AddIndex(
            model_name='perfilbusqueda',
            index=models.Index(fields=['empresa', 'estado'], name='perfiles_bu_empresa_104df2_idx'),
        ),
    ]
