# Generated by Django 6.0.5 on 2026-06-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_estadobusqueda_and_more'),
        ('postulantes', '0010_habilidad_nivelestudio_tipoempleo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilbusqueda',
            name='habilidades_tecnicas',
            field=models.ManyToManyField(blank=True, related_name='perfiles_requieren', to='postulantes.habilidad'),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='nivel_estudio_minimo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postulantes.nivelestudio'),
        ),
        migrations.AddField(
            model_name='perfilbusqueda',
            name='tipos_empleo',
            field=models.ManyToManyField(blank=True, related_name='perfiles_buscan', to='postulantes.tipoempleo'),
        ),
        migrations.AlterField(
            model_name='perfilbusqueda',
            name='habilidades_requeridas',
            field=models.TextField(blank=True, help_text='Lista de habilidades requeridas (separadas por comas)'),
        ),
    ]
