# Generated by Django 4.2 on 2026-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_perfilbusqueda_habilidades_tecnicas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_codigo', models.CharField(help_text='Código único del evento (ej: nueva_busqueda)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del tipo de alerta', max_length=100)),
                ('activar_email', models.BooleanField(default=True)),
                ('activar_whatsapp', models.BooleanField(default=True)),
                ('plantilla_email', models.TextField(help_text='Plantilla para el Email.')),
                ('plantilla_whatsapp', models.TextField(help_text='Plantilla para WhatsApp.')),
                ('destinatarios', models.CharField(choices=[('asignados', 'Solo selectores asignados a la búsqueda'), ('activos', 'Todos los selectores activos'), ('ambos', 'Ambos (Asignados y Activos)')], default='asignados', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración de Alerta',
                'verbose_name_plural': 'Configuraciones de Alerta',
                'db_table': 'configuracion_alertas',
            },
        ),
    ]
