# Generated by Django 4.2 on 2026-06-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selectores', '0004_selector_alias_publico'),
        ('empresas', '0015_configuracionalerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalerta',
            name='destinatario_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_especificas', to='selectores.selector'),
        ),
        migrations.AddField(
            model_name='configuracionalerta',
            name='destinatario_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_configuradas', to='selectores.gruposelector'),
        ),
        migrations.AlterField(
            model_name='configuracionalerta',
            name='destinatarios',
            field=models.CharField(choices=[('asignados', 'Solo selectores asignados a la búsqueda'), ('activos', 'Todos los selectores activos'), ('ambos', 'Ambos (Asignados y Activos)'), ('cierre', 'Solo el selector de Cierre (comisión)'), ('sourcing', 'Solo el selector de Sourcing (comisión)'), ('ambos_comision', 'Ambos selectores de la comisión (Sourcing y Cierre)'), ('grupo', 'Un grupo específico de selectores'), ('especifico', 'Un selector individual específico')], default='asignados', max_length=20),
        ),
    ]
