# Generated by Django 4.2 on 2026-06-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_configuracionalerta_destinatario_especifico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadobusqueda',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único identificador', max_length=50, null=True, unique=True),
        ),
    ]
