# Generated by Django 4.2 on 2026-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_estadobusqueda_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='perfilbusqueda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
