// Lista precargada de títulos de puesto frecuentes, para el combobox de búsquedas.
// Es solo una ayuda: el usuario puede elegir uno o escribir cualquier otro.
// Ampliable: agregá los que falten para tu mercado.

export const PUESTOS: string[] = [
  // ── Tecnología / IT ───────────────────────────────────────────
  "Desarrollador/a Frontend",
  "Desarrollador/a Backend",
  "Desarrollador/a Full Stack",
  "Desarrollador/a Mobile",
  "Desarrollador/a .NET",
  "Desarrollador/a Java",
  "Desarrollador/a Python",
  "Desarrollador/a PHP",
  "Desarrollador/a React",
  "Desarrollador/a Node.js",
  "Ingeniero/a de Software",
  "Arquitecto/a de Software",
  "Tech Lead",
  "Líder de Proyecto IT",
  "Scrum Master",
  "Product Owner",
  "Product Manager",
  "QA / Tester",
  "QA Automation",
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Administrador/a de Sistemas",
  "Administrador/a de Bases de Datos (DBA)",
  "Ingeniero/a de Datos",
  "Data Scientist",
  "Data Analyst",
  "Analista de BI",
  "Analista Funcional",
  "Analista Programador/a",
  "Especialista en Ciberseguridad",
  "Soporte Técnico / Help Desk",
  "Diseñador/a UX/UI",
  "Cloud Engineer",
  "Especialista en Redes",
  "Consultor/a SAP",
  "Consultor/a IT",

  // ── Administración / Finanzas ─────────────────────────────────
  "Administrativo/a",
  "Asistente Administrativo/a",
  "Recepcionista",
  "Secretario/a",
  "Asistente de Gerencia",
  "Contador/a",
  "Analista Contable",
  "Auxiliar Contable",
  "Tesorero/a",
  "Analista de Cuentas por Pagar",
  "Analista de Cuentas por Cobrar",
  "Analista de Costos",
  "Analista Financiero/a",
  "Gerente de Administración y Finanzas",
  "Jefe/a de Administración",
  "Auditor/a Interno/a",
  "Liquidador/a de Sueldos",
  "Analista de Impuestos",

  // ── Recursos Humanos ──────────────────────────────────────────
  "Analista de Recursos Humanos",
  "Generalista de RRHH",
  "Reclutador/a IT",
  "Selector/a de Personal",
  "Responsable de Capacitación",
  "Business Partner de RRHH",
  "Jefe/a de Recursos Humanos",
  "Gerente de Recursos Humanos",
  "Responsable de Payroll",

  // ── Comercial / Ventas ────────────────────────────────────────
  "Vendedor/a",
  "Ejecutivo/a de Ventas",
  "Representante Comercial",
  "Key Account Manager",
  "Account Manager",
  "Asesor/a Comercial",
  "Supervisor/a de Ventas",
  "Jefe/a de Ventas",
  "Gerente Comercial",
  "Vendedor/a de Salón",
  "Cajero/a",
  "Telemarketer / Televentas",
  "Sales Development Representative (SDR)",
  "Business Development Manager",

  // ── Marketing / Comunicación ──────────────────────────────────
  "Analista de Marketing",
  "Community Manager",
  "Social Media Manager",
  "Especialista en Marketing Digital",
  "Especialista en SEO/SEM",
  "Diseñador/a Gráfico/a",
  "Content Manager",
  "Brand Manager",
  "Jefe/a de Marketing",
  "Gerente de Marketing",
  "Redactor/a / Copywriter",
  "Productor/a Audiovisual",

  // ── Operaciones / Logística / Industria ───────────────────────
  "Operario/a de Producción",
  "Operario/a de Depósito",
  "Supervisor/a de Producción",
  "Jefe/a de Producción",
  "Gerente de Operaciones",
  "Analista de Logística",
  "Coordinador/a de Logística",
  "Jefe/a de Depósito",
  "Encargado/a de Almacén",
  "Chofer / Conductor/a",
  "Repartidor/a",
  "Planificador/a de la Producción",
  "Analista de Compras",
  "Comprador/a",
  "Jefe/a de Compras",
  "Analista de Calidad",
  "Responsable de Calidad",
  "Técnico/a de Mantenimiento",
  "Jefe/a de Mantenimiento",
  "Ingeniero/a Industrial",
  "Ingeniero/a Mecánico/a",
  "Ingeniero/a Electrónico/a",
  "Ingeniero/a Civil",
  "Ingeniero/a en Seguridad e Higiene",
  "Técnico/a Electromecánico/a",
  "Soldador/a",
  "Electricista",
  "Electricista Automotor",
  "Mecánico/a",

  // ── Atención al cliente ───────────────────────────────────────
  "Atención al Cliente",
  "Representante de Atención al Cliente",
  "Operador/a de Call Center",
  "Supervisor/a de Call Center",
  "Customer Success Manager",

  // ── Salud ─────────────────────────────────────────────────────
  "Médico/a",
  "Enfermero/a",
  "Kinesiólogo/a",
  "Psicólogo/a",
  "Farmacéutico/a",
  "Técnico/a de Laboratorio",
  "Recepcionista de Clínica",
  "Cuidador/a",

  // ── Legal ─────────────────────────────────────────────────────
  "Abogado/a",
  "Procurador/a",
  "Asistente Legal",
  "Escribano/a",

  // ── Gastronomía / Hotelería / Turismo ─────────────────────────
  "Cocinero/a",
  "Ayudante de Cocina",
  "Mozo/a / Camarero/a",
  "Bartender",
  "Encargado/a de Local",
  "Recepcionista de Hotel",
  "Conserje",

  // ── Construcción / Oficios ────────────────────────────────────
  "Maestro/a Mayor de Obra",
  "Albañil",
  "Plomero/a",
  "Pintor/a",
  "Carpintero/a",
  "Gasista",

  // ── Educación ─────────────────────────────────────────────────
  "Docente",
  "Profesor/a",
  "Capacitador/a",
  "Coordinador/a Académico/a",

  // ── Dirección / Gerencia ──────────────────────────────────────
  "Gerente General",
  "Director/a Ejecutivo/a (CEO)",
  "Director/a de Operaciones (COO)",
  "Director/a Financiero/a (CFO)",
  "Director/a de Tecnología (CTO)",
  "Jefe/a de Proyecto",
  "Coordinador/a General",
];
