// Catálogo de rubros / sectores para el dropdown de Empresa.
// Se siembra en la tabla `rubros` (migración 0011) para que aparezca en todas
// las consultoras. El usuario igual puede crear uno nuevo con "…o nuevo rubro".
export const RUBROS: string[] = [
  "Tecnología / IT",
  "Software y Servicios Informáticos",
  "Banca y Finanzas",
  "Seguros",
  "Salud / Medicina",
  "Educación",
  "Retail / Comercio",
  "Consumo Masivo",
  "Industria / Manufactura",
  "Automotriz",
  "Construcción",
  "Inmobiliaria",
  "Agro / Agroindustria",
  "Alimentos y Bebidas",
  "Energía",
  "Petróleo y Gas",
  "Minería",
  "Logística y Transporte",
  "Telecomunicaciones",
  "Medios y Comunicación",
  "Publicidad y Marketing",
  "Turismo y Hotelería",
  "Gastronomía",
  "Legal / Estudios Jurídicos",
  "Contabilidad y Auditoría",
  "Consultoría",
  "Recursos Humanos",
  "Farmacéutica",
  "Química",
  "Textil e Indumentaria",
  "Electrónica",
  "Servicios Públicos",
  "ONG / Tercer Sector",
  "Gobierno / Sector Público",
  "Entretenimiento",
  "Deportes",
  "Aeronáutica",
  "Seguridad",
  "Importación / Exportación",
  "Otro",
];
