# Generated by Django 4.2 on 2026-05-14 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_porcentaje_empresa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comision_porcentaje_selector', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la comisión facturada a la empresa', max_digits=12)),
                ('monto_empresa', models.DecimalField(decimal_places=2, help_text='Ganancia neta para la consultora', max_digits=12)),
                ('monto_selector', models.DecimalField(decimal_places=2, help_text='Monto a pagar al selector freelance', max_digits=12)),
                ('estado', models.CharField(choices=[('calculada', 'Calculada'), ('pendiente_cobro', 'Pendiente de Cobro (Empresa)'), ('cobrada', 'Cobrada (Empresa)'), ('pendiente_pago', 'Pendiente de Pago (Selector)'), ('pagada', 'Pagada (Selector)'), ('garantia', 'En Período de Garantía'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='calculada', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_trabajo', models.DateField()),
                ('fecha_vencimiento_garantia', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'comisiones',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='PagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='transferencia', max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('banco_destino', models.CharField(blank=True, max_length=100)),
                ('cuenta_destino', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='comisiones.comision')),
            ],
            options={
                'db_table': 'pagos_comision',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
