# Generated by Django 4.2 on 2026-05-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comisiones', '0001_initial'),
        ('selectores', '0001_initial'),
        ('empresas', '0002_initial'),
        ('postulaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_pagadas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='comision',
            name='postulacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='postulaciones.postulacion'),
        ),
        migrations.AddField(
            model_name='comision',
            name='selector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_generadas', to='selectores.selector'),
        ),
    ]
