# Generated by Django 6.0.5 on 2026-06-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0002_initial'),
        ('selectores', '0004_selector_alias_publico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_sourcing', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje para quien aporta el candidato', max_digits=5)),
                ('porcentaje_cierre', models.DecimalField(decimal_places=2, default=40.0, help_text='Porcentaje para quien cierra la búsqueda', max_digits=5)),
            ],
            options={
                'verbose_name': 'Esquema de Comisión',
                'verbose_name_plural': 'Esquemas de Comisión',
                'db_table': 'esquemas_comision',
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='aplica_clawback',
            field=models.BooleanField(default=False, help_text='Si el candidato no superó la garantía'),
        ),
        migrations.AddField(
            model_name='comision',
            name='monto_cierre',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto para el selector que cerró la posición', max_digits=12),
        ),
        migrations.AddField(
            model_name='comision',
            name='monto_devolucion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto a descontar por clawback', max_digits=12),
        ),
        migrations.AddField(
            model_name='comision',
            name='monto_sourcing',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto para el selector que aportó el candidato', max_digits=12),
        ),
        migrations.AddField(
            model_name='comision',
            name='porcentaje_cierre',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='comision',
            name='porcentaje_sourcing',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='comision',
            name='selector_sourcing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_sourcing', to='selectores.selector'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='monto_selector',
            field=models.DecimalField(decimal_places=2, help_text='Monto total a pagar a los selectores', max_digits=12),
        ),
    ]
