# Generated by Django 4.2 on 2026-06-02 18:19

from django.db import migrations, models
import django.db.models.deletion

def migrar_estados_comision(apps, schema_editor):
    EstadoComision = apps.get_model('comisiones', 'EstadoComision')
    Comision = apps.get_model('comisiones', 'Comision')

    # Crear estados por defecto
    estados_defecto = [
        ('calculada', 'Calculada', '#6c757d', 'Comisión calculada automáticamente'),
        ('pendiente_cobro', 'Pendiente de Cobro (Empresa)', '#fd7e14', 'Pendiente de cobro a la empresa'),
        ('cobrada', 'Cobrada (Empresa)', '#20c997', 'Cobrada a la empresa'),
        ('pendiente_pago', 'Pendiente de Pago (Selector)', '#0d6efd', 'Pendiente de pago al selector'),
        ('pagada', 'Pagada (Selector)', '#198754', 'Comisión pagada al selector'),
        ('garantia', 'En Período de Garantía', '#ffc107', 'En período de garantía comercial'),
        ('completada', 'Completada', '#212529', 'Proceso de comisión completado'),
        ('anulada', 'Anulada', '#dc3545', 'Comisión anulada'),
    ]

    estados_map = {}
    for codigo, nombre, color, desc in estados_defecto:
        estado_obj, _ = EstadoComision.objects.get_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'color': color,
                'descripcion': desc,
                'no_borrable': True
            }
        )
        estados_map[codigo] = estado_obj

    # Asignar foreign key a comisiones existentes
    for comision in Comision.objects.all():
        old_val = comision.estado_old
        if old_val in estados_map:
            comision.estado = estados_map[old_val]
        else:
            # Fallback a calculada
            comision.estado = estados_map['calculada']
        comision.save()

class Migration(migrations.Migration):

    dependencies = [
        ('selectores', '0004_selector_alias_publico'),
        ('comisiones', '0003_esquemacomision_comision_aplica_clawback_and_more'),
    ]

    operations = [
        # 1. Renombrar la columna estado a estado_old
        migrations.RenameField(
            model_name='comision',
            old_name='estado',
            new_name='estado_old',
        ),
        # 2. Crear el modelo EstadoComision
        migrations.CreateModel(
            name='EstadoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único identificador (ej: pagada)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre visible (ej: Pagada)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del estado')),
                ('color', models.CharField(default='#34c759', help_text='Código de color hexadecimal', max_length=7)),
                ('no_borrable', models.BooleanField(default=False, help_text='Evita la eliminación de estados críticos')),
                ('activar_email', models.BooleanField(default=False)),
                ('activar_whatsapp', models.BooleanField(default=False)),
                ('plantilla_email', models.TextField(blank=True, help_text='Variables: {nombre_selector}, {monto_comision}, {candidato_nombre}, {puesto}, {empresa_nombre}')),
                ('plantilla_whatsapp', models.TextField(blank=True, help_text='Variables: {nombre_selector}, {monto_comision}, {candidato_nombre}, {puesto}, {empresa_nombre}')),
                ('destinatarios', models.CharField(choices=[('cierre', 'Solo el selector de Cierre (comisión)'), ('sourcing', 'Solo el selector de Sourcing (comisión)'), ('ambos_comision', 'Ambos selectores de la comisión (Sourcing y Cierre)'), ('grupo', 'Un grupo específico de selectores'), ('especifico', 'Un selector individual específico'), ('activos', 'Todos los selectores activos')], default='cierre', max_length=20)),
                ('destinatario_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_comision_alertas_especificas', to='selectores.selector')),
                ('destinatario_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_comision_alertas', to='selectores.gruposelector')),
            ],
            options={
                'verbose_name': 'Estado de Comisión',
                'verbose_name_plural': 'Estados de Comisión',
                'db_table': 'estados_comision',
            },
        ),
        # 3. Agregar el nuevo campo de ForeignKey 'estado' (inicialmente nullable)
        migrations.AddField(
            model_name='comision',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='comisiones.estadocomision'),
        ),
        # 4. Ejecutar RunPython para crear los estados y mapear las comisiones existentes
        migrations.RunPython(migrar_estados_comision),
    ]
