# Generated by Django 4.2 on 2026-06-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0004_comision_estado_old_estadocomision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='estado_old',
        ),
        migrations.AlterField(
            model_name='comision',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='comisiones.estadocomision'),
        ),
    ]
