# Generated by Django 4.2 on 2026-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0005_remove_comision_estado_old_alter_comision_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocomision',
            name='destinatarios',
            field=models.CharField(choices=[('asignados', 'Solo selectores asignados a la búsqueda'), ('activos', 'Todos los selectores activos'), ('ambos', 'Ambos (Asignados y Activos)'), ('cierre', 'Solo el selector de Cierre (comisión)'), ('sourcing', 'Solo el selector de Sourcing (comisión)'), ('ambos_comision', 'Ambos selectores de la comisión (Sourcing y Cierre)'), ('grupo', 'Un grupo específico de selectores'), ('especifico', 'Un selector individual específico')], default='cierre', max_length=20),
        ),
    ]
