# Generated by Django 4.2 on 2026-05-14 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva Asignación'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('completada', 'Completada (Perfil Cubierto)'), ('cancelada', 'Cancelada')], default='nueva', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_limite_entrega', models.DateField(blank=True, null=True)),
                ('cantidad_postulantes_esperados', models.PositiveIntegerField(default=3, help_text='Cantidad mínima de postulantes esperados')),
                ('notas', models.TextField(blank=True, help_text='Instrucciones especiales')),
                ('cantidad_postulantes_enviados', models.PositiveIntegerField(default=0)),
                ('cantidad_contratados', models.PositiveIntegerField(default=0)),
                ('perfil_busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_selectores', to='empresas.perfilbusqueda')),
            ],
            options={
                'db_table': 'asignaciones_busqueda',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('especializacion', models.CharField(choices=[('it', 'IT'), ('admin', 'Administrativo'), ('ejecutivo', 'Ejecutivo/Jerárquico'), ('general', 'General (Múltiples áreas)')], default='general', max_length=20)),
                ('experiencia_anos', models.PositiveIntegerField(default=0, help_text='Años de experiencia en selección')),
                ('descripcion_perfil', models.TextField(blank=True, help_text='Descripción de fortalezas y especialidades')),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pausado', 'Pausado'), ('baja', 'Baja')], default='activo', max_length=20)),
                ('cuit', models.CharField(help_text='Para facturación de comisiones', max_length=20, unique=True)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('cbu', models.CharField(blank=True, help_text='CBU para transferencias', max_length=22)),
                ('alias_cvu', models.CharField(blank=True, help_text='CVU o alias', max_length=50)),
                ('cantidad_postulantes_enviados', models.PositiveIntegerField(default=0)),
                ('cantidad_contratados', models.PositiveIntegerField(default=0)),
                ('tasa_efectividad', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de postulantes que fueron contratados', max_digits=5)),
                ('comision_porcentaje_defecto', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje de comisión (se divide con la empresa)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('google_contact_id', models.CharField(blank=True, help_text='ID del contacto en Google Contacts', max_length=255, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'selectores',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSelectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='selectores.asignacionbusqueda')),
            ],
            options={
                'db_table': 'historial_selectores',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='asignacionbusqueda',
            name='selector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_busqueda', to='selectores.selector'),
        ),
        migrations.AddIndex(
            model_name='selector',
            index=models.Index(fields=['estado'], name='selectores_estado_1eca56_idx'),
        ),
        migrations.AddIndex(
            model_name='selector',
            index=models.Index(fields=['especializacion'], name='selectores_especia_af1a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionbusqueda',
            index=models.Index(fields=['selector', 'estado'], name='asignacione_selecto_925cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionbusqueda',
            index=models.Index(fields=['perfil_busqueda', 'estado'], name='asignacione_perfil__87766b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionbusqueda',
            unique_together={('selector', 'perfil_busqueda')},
        ),
    ]
