# Generated by Django 4.2 on 2026-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='dni',
            field=models.CharField(blank=True, help_text='DNI del selector', max_length=20, null=True, unique=True),
        ),
    ]
