# Generated by Django 4.2 on 2026-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectores', '0002_selector_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del grupo de selectores')),
            ],
            options={
                'verbose_name': 'Grupo de Selectores',
                'verbose_name_plural': 'Grupos de Selectores',
                'db_table': 'grupos_selector',
            },
        ),
        migrations.AddField(
            model_name='selector',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='selectores', to='selectores.gruposelector'),
        ),
    ]
