# Generated by Django 6.0.5 on 2026-06-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectores', '0003_gruposelector_selector_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='alias_publico',
            field=models.SlugField(blank=True, help_text='Alias para el portal público (ej: juan-perez)', max_length=100, null=True, unique=True),
        ),
    ]
